"""Inline sibling modules into a single Kaggle kernel code_file.

Output: kaggle_kernel/kernel_l2_supcon_ncm/dist/l2_kernel.py

Run: python kaggle_kernel/kernel_l2_supcon_ncm/build.py
"""
from __future__ import annotations

import re
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE / "dist" / "l2_kernel.py"

# Order matters: dependency-topological.
MODULES = ["boot", "config", "features", "ote", "data",
           "embedder", "ncm", "cv", "main"]

HEADER = '''"""L2 SupCon-NCM kernel — assembled from sibling modules via build.py.

DO NOT edit this file directly. Edit the source modules (boot.py,
config.py, features.py, ote.py, data.py, embedder.py, ncm.py, cv.py,
main.py) and re-run
    python kaggle_kernel/kernel_l2_supcon_ncm/build.py
to regenerate.
"""
'''

SINGLE_RE = re.compile(
    r"^\s*from\s+(" + "|".join(MODULES) + r")\s+import\s+.*$|"
    r"^\s*import\s+(" + "|".join(MODULES) + r")\s*$",
    re.MULTILINE,
)
MULTI_RE = re.compile(
    r"^\s*from\s+(" + "|".join(MODULES) + r")\s+import\s+\([^)]*\)\s*$",
    re.MULTILINE | re.DOTALL,
)


def strip_siblings(text: str) -> str:
    text = MULTI_RE.sub("", text)
    text = SINGLE_RE.sub("", text)
    return text


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    parts: list[str] = [HEADER, "from __future__ import annotations\n"]
    for mod in MODULES:
        src = (HERE / f"{mod}.py").read_text()
        # Strip first docstring + per-module __future__ imports.
        src = re.sub(r'^"""[\s\S]*?"""\s*\n?', "", src, count=1)
        src = re.sub(r"^from __future__ import.*\n?", "",
                     src, flags=re.MULTILINE)
        parts.append(f"\n# ===== {mod}.py =====\n")
        parts.append(strip_siblings(src))
    parts.append('\nif __name__ == "__main__":\n    main()\n')
    OUT.write_text("".join(parts))
    print(f"wrote {OUT}  ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
