"""Concatenate modular sources into a single Kaggle-uploadable script.

Kaggle's `kernels push` only uploads the `code_file`, so sibling imports
from features/model/train/data/search modules won't resolve on the kernel
side. This build step stitches them into `dist/nn_digit_hp_tune.py` with
the same top-level semantics (env vars, CLI entrypoint) intact.

Run: `python kaggle_kernel/kernel_nn_hp_tune/build.py`
Then: `cd kaggle_kernel/kernel_nn_hp_tune/dist && kaggle kernels push`
"""
from __future__ import annotations
import re
import shutil
from pathlib import Path

HERE = Path(__file__).parent
DIST = HERE / "dist"

# Order matters: dependencies first, then the orchestrator.
MODULES = ["features.py", "model.py", "train.py", "data.py", "search.py"]
ENTRY = "nn_digit_hp_tune.py"

# Strip sibling imports (single-line and parenthesized multi-line),
# `import foo` bare forms, the local sys.path.insert, and all
# `from __future__` lines (we hoist one to the top of the built file).
SIBLING_FROM_SINGLE = re.compile(
    r"^\s*from\s+(features|model|train|data|search)\s+import\s+[^\(\n]+$",
    re.MULTILINE,
)
SIBLING_FROM_MULTI = re.compile(
    r"^\s*from\s+(features|model|train|data|search)\s+import\s*\([^)]*\)\s*$",
    re.MULTILINE | re.DOTALL,
)
SIBLING_IMPORT_BARE = re.compile(
    r"^\s*import\s+(features|model|train|data|search)\s*$",
    re.MULTILINE,
)
SYSPATH_INSERT_RE = re.compile(
    r"^\s*sys\.path\.insert\(0,\s*str\(Path\(__file__\)\.parent\)\).*$",
    re.MULTILINE,
)
FUTURE_IMPORT_RE = re.compile(
    r"^\s*from\s+__future__\s+import\s+[^\n]+$",
    re.MULTILINE,
)


def clean(src: str) -> str:
    src = SIBLING_FROM_MULTI.sub("", src)
    src = SIBLING_FROM_SINGLE.sub("", src)
    src = SIBLING_IMPORT_BARE.sub("", src)
    src = SYSPATH_INSERT_RE.sub("", src)
    src = FUTURE_IMPORT_RE.sub("", src)
    return src


def main() -> None:
    DIST.mkdir(exist_ok=True)
    parts = []
    parts.append("# AUTOGENERATED — built by build.py from sibling modules\n")
    parts.append("# Modules (in order): " + ", ".join(MODULES + [ENTRY]) + "\n")
    parts.append("from __future__ import annotations\n\n")
    for name in MODULES:
        src = (HERE / name).read_text()
        parts.append(f"# ---- {name} " + "-" * (72 - len(name)) + "\n")
        parts.append(clean(src).rstrip() + "\n\n")
    entry_src = clean((HERE / ENTRY).read_text())
    parts.append(f"# ---- {ENTRY} " + "-" * (72 - len(ENTRY)) + "\n")
    parts.append(entry_src)
    out = DIST / ENTRY
    out.write_text("".join(parts))
    # Copy metadata verbatim
    shutil.copy(HERE / "kernel-metadata.json", DIST / "kernel-metadata.json")
    print(f"built {out}  ({out.stat().st_size/1024:.1f} KB)")
    print(f"metadata: {DIST / 'kernel-metadata.json'}")


if __name__ == "__main__":
    main()
