"""Inline sibling modules into a single Kaggle-kernel code_file.

Kaggle kernel push only uploads the one `code_file` referenced in
kernel-metadata.json. This script concatenates boot/config/features/
model/cv/main into a single dist/trompt_kernel.py that's self-contained
and push-ready. Each sibling's `from <sibling> import ...` lines are
stripped; the symbols resolve via the flattened namespace.

Run:
    python kaggle_kernel/kernel_trompt/build.py

Output: kaggle_kernel/kernel_trompt/dist/trompt_kernel.py
"""
from __future__ import annotations
import re
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE / "dist" / "trompt_kernel.py"

# Order matters: dependency-topological.
MODULES = ["boot", "config", "features", "model", "cv", "main"]

HEADER = '''"""Trompt kernel — assembled from sibling modules via build.py.

DO NOT edit this file directly. Edit the source modules (boot.py,
config.py, features.py, model.py, cv.py, main.py) and re-run
    python kaggle_kernel/kernel_trompt/build.py
to regenerate.
"""
'''

# Strip lines that import from this package's modules (they become
# local-namespace references after concatenation). Handles both
# single-line `from x import a, b` and multi-line
# `from x import (\n    a,\n    b,\n)` forms.
SINGLE_RE = re.compile(
    r"^\s*from\s+(" + "|".join(MODULES) + r")\s+import\s+.*$|"
    r"^\s*import\s+(" + "|".join(MODULES) + r")\s*$",
    re.MULTILINE,
)
MULTI_RE = re.compile(
    r"^\s*from\s+(" + "|".join(MODULES) + r")\s+import\s+\([^)]*\)\s*$",
    re.MULTILINE | re.DOTALL,
)


def strip_siblings(text: str) -> str:
    text = MULTI_RE.sub("", text)
    text = SINGLE_RE.sub("", text)
    return text


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    # Drop ALL module docstrings + __future__ imports from sources, then
    # hoist a single `from __future__ import annotations` to the top
    # right after the header docstring (Python requires it before any
    # other import / non-docstring code).
    parts: list[str] = [HEADER, "from __future__ import annotations\n"]
    for mod in MODULES:
        src = (HERE / f"{mod}.py").read_text()
        src = re.sub(r'^"""[\s\S]*?"""\s*\n?', "", src, count=1)
        src = re.sub(r"^from __future__ import.*\n?", "",
                     src, flags=re.MULTILINE)
        parts.append(f"\n# ===== {mod}.py =====\n")
        parts.append(strip_siblings(src))
    parts.append('\nif __name__ == "__main__":\n    main()\n')
    OUT.write_text("".join(parts))
    print(f"wrote {OUT}  ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
