"""T1 — format borderline rows into subagent prompt batches.

Builds the haiku-friendly prompt per the template in
prompts/subagent_llm_judge.md. Numeric columns are rounded to 2dp to
keep token count down without losing rule-relevant precision.

Usage:
  from T1_format_batch import build_batch_prompt, FEATURE_KEYS
  prompt_text = build_batch_prompt(df_subset)
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

# 19 raw test features, in the order the prompt template expects.
FEATURE_KEYS = [
    "Soil_Moisture", "Rainfall_mm", "Temperature_C", "Wind_Speed_kmh",
    "Mulching_Used", "Crop_Growth_Stage",
    "Soil_pH", "Humidity", "Soil_Type", "Organic_Carbon",
    "Electrical_Conductivity", "Sunlight_Hours", "Crop_Type", "Season",
    "Irrigation_Type", "Water_Source", "Field_Area_hectare",
    "Previous_Irrigation_mm", "Region",
]

NUMERIC_KEYS = {
    "Soil_Moisture", "Rainfall_mm", "Temperature_C", "Wind_Speed_kmh",
    "Soil_pH", "Humidity", "Organic_Carbon", "Electrical_Conductivity",
    "Sunlight_Hours", "Field_Area_hectare", "Previous_Irrigation_mm",
}


HEADER = """Task: classify N rows of synthetic irrigation-need data as
Low / Medium / High.

Background: synthetic data generated by a NN trained on a 10k-row
real-world dataset. We have reverse-engineered an integer rule that
matches the labels ~98.4% of the time:

  dry     = (Soil_Moisture < 25)         # 0 or 1
  norain  = (Rainfall_mm   < 300)        # 0 or 1
  hot     = (Temperature_C > 30)         # 0 or 1
  windy   = (Wind_Speed_kmh > 10)        # 0 or 1
  nomulch = (Mulching_Used == "No")      # 0 or 1
  Kc      = 2 if Crop_Growth_Stage in {Flowering, Vegetative} else 0
  score   = 2*(dry + norain) + (hot + windy + nomulch) + Kc
  Low if score <= 3 ; Medium if 4 <= score <= 6 ; High if score >= 7

About 1.6% of rows are "flipped" by the NN to a neighbouring class
based on non-rule features (Humidity, Soil_pH, Previous_Irrigation_mm,
Electrical_Conductivity, Organic_Carbon, Sunlight_Hours,
Field_Area_hectare, Crop_Type, Region, Season, Soil_Type,
Irrigation_Type, Water_Source). The NN over-irrigates when humidity
is low + recent irrigation small + organic carbon low.

For each row I give you, reply in this EXACT format (one block per row):

ROW <test_id>
RULE_SCORE: <int>
RULE_PRED: <Low|Medium|High>
FINAL: <Low|Medium|High>
CONF: <0.0-1.0>
REASON: <<=15 words>

Do not include any other text — no preamble, no summary. Just the
ROW blocks.

ROWS TO CLASSIFY:
"""


def _format_value(k: str, v) -> str:
    if k in NUMERIC_KEYS:
        try:
            return f"{float(v):.2f}"
        except (TypeError, ValueError):
            return str(v)
    return str(v)


def format_row(test_id: int, row_features: dict) -> str:
    """Format one test row as a single line."""
    parts = [f"ROW {int(test_id)}"]
    for k in FEATURE_KEYS:
        parts.append(f"{k}={_format_value(k, row_features.get(k))}")
    return " ".join(parts)


def build_batch_prompt(df_subset: pd.DataFrame, test_df: pd.DataFrame) -> str:
    """Build full prompt text for a batch of borderline rows.

    df_subset: borderline table slice with at least 'test_id' column.
    test_df: full test.csv DataFrame with feature columns.
    """
    # Index test_df by id for fast lookup
    if test_df.index.name != "id":
        test_df = test_df.set_index("id", drop=False)
    lines = [HEADER]
    for _, r in df_subset.iterrows():
        tid = int(r["test_id"])
        feats = test_df.loc[tid].to_dict()
        lines.append(format_row(tid, feats))
    return "\n".join(lines)


def estimate_tokens(prompt: str) -> int:
    """Rough token estimate: 1 token ~ 4 chars."""
    return len(prompt) // 4


def main():
    """Smoke check: print a 1-row, 5-row, 50-row prompt and token estimates."""
    ART = Path("scripts/artifacts")
    DATA = Path("data")
    bord = pd.read_csv(ART / "T1_borderline_top500.csv")
    test = pd.read_csv(DATA / "test.csv")
    for n in (1, 5, 50, 100):
        sub = bord.head(n)
        p = build_batch_prompt(sub, test)
        print(f"\n=== batch n={n}, chars={len(p)}, est tokens={estimate_tokens(p)} ===")
        if n == 1:
            print(p)


if __name__ == "__main__":
    main()
