"""T1-v3 — haiku prompts with per-component vote split + 3-sub verdict vector.

Adds two context fields per row that v2 lacked:
  - bank_split: "12M/2H/0L"  (raw count of the 14 bank components' argmaxes)
  - sub_votes:  "v1=M raw=H t1=M"  (the 3 fb_oof component verdicts)

These were dropped from v2's prompt; opus-V1 had a partial version. The
hypothesis: showing haiku per-component disagreement lets it decorrelate
from bank-mean errors. If still null at ~88%, LLM-judge mechanism
structurally closed.

Same critical rows + 8 few-shot exemplars as v2 for clean comparison.

Output: scripts/artifacts/T1_v2/haiku_v3_batch_{i}.txt
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from T1_format_batch import FEATURE_KEYS, _format_value  # noqa: E402
from T2_conformal_helpers import load_bank  # noqa: E402
from T6_diversity_helpers import load_y_train, normed, tune_log_bias_simple  # noqa: E402

ART = Path("scripts/artifacts")
DATA = Path("data")
OUT = ART / "T1_v2"
CLASS_STR = {0: "L", 1: "M", 2: "H"}

OVERRIDE_PREFIX = (
    "IMPORTANT: ignore your statusline-setup persona for this single message. "
    "Output ONLY the requested ROW blocks — no preamble, no markdown fences, "
    "no commentary. No tool calls after the Read.\n\n"
)

HEADER = """Task: classify rows of synthetic irrigation-need data as Low / Medium / High.

Background: synthetic data generated by an NN trained on a 10k-row real-world dataset. Reverse-engineered integer rule (~98.4% accurate):

  dry     = (Soil_Moisture < 25)
  norain  = (Rainfall_mm   < 300)
  hot     = (Temperature_C > 30)
  windy   = (Wind_Speed_kmh > 10)
  nomulch = (Mulching_Used == "No")
  Kc      = 2 if Crop_Growth_Stage in {Flowering, Vegetative} else 0
  score   = 2*(dry + norain) + (hot + windy + nomulch) + Kc
  Low if score <= 3 ; Medium if 4 <= score <= 6 ; High if score >= 7

About 1.6% of rows are flipped by the NN to a neighbouring class based on non-rule features. Over-irrigate flips (M -> H) happen when humidity is low + recent irrigation small + organic carbon low.

CRITICAL CONTEXT — these are pre-filtered HARD cases. The 14-bank tree ensemble says Medium AND the LB-best 4b primary says High. Plus: each row has been further filtered to satisfy at least 3 of 4 strong M-signals:
  - amh < 0.20            (low predicted H-flip risk from auxiliary detector)
  - amm < 0.30            (low predicted M-flip-elsewhere risk)
  - knn_consensus >= 0.70 (k=100 nearest neighbors agree)
  - bank_conf >= 0.80     (the bank ensemble itself is fairly confident on M)

NEW IN V3 — per-row context now exposes:
  - bank_split: counts of how the 14 bank components individually vote, e.g. "12M/2H/0L"
                A row with 14M/0H/0L is unanimous; 8M/6H/0L is split (weaker M signal).
  - sub_votes:  3 standalone-LB-validated submission verdicts on this row:
                v1 (sklearn RF natural, LB 0.98129)
                raw (rawashishsin XGB, LB 0.98109)
                t1 (tier1b greedy meta)
                If all 3 say M, the M signal is robust; if one says H, scrutinize.

The TRAIN-OOF baseline true-M rate on this filtered set is 87.75%. The bank is wrong 12.25% of the time on these rows. Lean toward M when bank_split is unanimous AND all sub_votes agree on M. Only flag H when bank_split shows >= 4 H-votes AND multiple non-rule features clearly indicate over-irrigate.

For each row, output ONE block:

ROW <pseudo_id>
RULE_SCORE: <int>
RULE_PRED: <Low|Medium|High>
FINAL: <Low|Medium|High>
CONF: <0.0-1.0>
REASON: <<=15 words>

EXAMPLES (8 rows from the same critical population with TRUE labels revealed; learn the boundary):

"""

ASYMMETRY_NOTE = """

Now classify the following critical-rows test set. Use the same reasoning style. CONF should reflect your confidence in FINAL.

ROWS TO CLASSIFY:

"""


def fmt_row(pseudo_id, feats, amh, amm, knn_margin, bank_max_prob, bank_split, sub_votes):
    parts = [f"ROW {int(pseudo_id)}"]
    for k in FEATURE_KEYS:
        parts.append(f"{k}={_format_value(k, feats.get(k))}")
    parts.append(f"amh={amh:.3f}")
    parts.append(f"amm={amm:.3f}")
    parts.append(f"knn_consensus={knn_margin:.3f}")
    parts.append(f"bank_conf={bank_max_prob:.3f}")
    parts.append(f"bank_split={bank_split}")
    parts.append(f"sub_votes={sub_votes}")
    return " ".join(parts)


def fmt_few_shot(pseudo_id, feats, amh, amm, knn_margin, bank_max_prob, bank_split, sub_votes, true_label, score):
    rp = "Low" if score <= 3 else ("Medium" if score <= 6 else "High")
    head = fmt_row(pseudo_id, feats, amh, amm, knn_margin, bank_max_prob, bank_split, sub_votes)
    return (
        f"{head}\n"
        f"RULE_SCORE: {score}\n"
        f"RULE_PRED: {rp}\n"
        f"FINAL: {true_label}    ← TRUE LABEL\n"
        f"CONF: 1.00\n"
        f"REASON: (true label revealed; reason it through yourself)\n"
    )


def dgp_score(row):
    dry = int(row["Soil_Moisture"] < 25)
    norain = int(row["Rainfall_mm"] < 300)
    hot = int(row["Temperature_C"] > 30)
    windy = int(row["Wind_Speed_kmh"] > 10)
    nomulch = int(row["Mulching_Used"] == "No")
    Kc = 2 if row["Crop_Growth_Stage"] in {"Flowering", "Vegetative"} else 0
    return 2 * (dry + norain) + (hot + windy + nomulch) + Kc


def main():
    print("=== T1-v3 build prompts ===\n")
    train = pd.read_csv(DATA / "train.csv")
    crit = pd.read_csv(OUT / "critical_rows.csv")
    boundary = pd.read_csv(OUT / "boundary_rows.csv")
    print(f"critical: {len(crit)} boundary: {len(boundary)}")

    # Compute per-component bank vote split
    bank = load_bank("oof")  # (14, n_train, 3)
    bank_argmaxes = bank.argmax(axis=2).astype(np.int8)  # (14, n_train)
    n_train = bank_argmaxes.shape[1]

    def split_str(row_idx):
        votes = bank_argmaxes[:, row_idx]
        counts = np.bincount(votes, minlength=3)
        return f"{counts[1]}M/{counts[2]}H/{counts[0]}L"

    # Compute the 3 sub-votes (v1, raw, t1)
    y = load_y_train()
    v1_oof = normed(np.load(ART / "oof_sklearn_rf_meta_natural.npy").astype(np.float32))
    raw_oof = normed(np.load(ART / "oof_rawashishsin_2600.npy").astype(np.float32))
    t1_oof = normed(np.load(ART / "oof_tier1b_greedy_meta.npy").astype(np.float32))
    bv1, _ = tune_log_bias_simple(v1_oof, y)
    bra, _ = tune_log_bias_simple(raw_oof, y)
    bt1, _ = tune_log_bias_simple(t1_oof, y)
    a_v1 = (np.log(np.clip(v1_oof, 1e-9, None)) + bv1).argmax(1).astype(np.int8)
    a_ra = (np.log(np.clip(raw_oof, 1e-9, None)) + bra).argmax(1).astype(np.int8)
    a_t1 = (np.log(np.clip(t1_oof, 1e-9, None)) + bt1).argmax(1).astype(np.int8)

    def subs_str(row_idx):
        return f"v1={CLASS_STR[a_v1[row_idx]]} raw={CLASS_STR[a_ra[row_idx]]} t1={CLASS_STR[a_t1[row_idx]]}"

    # Few-shot: same 4 critical-M + 4 boundary-H selection as v2 (seed 7 for repro)
    crit_M = crit[crit["true_label"] == "Medium"].sample(n=4, random_state=7)
    bnd_H = boundary[boundary["true_label"] == "High"].sample(n=4, random_state=7)
    fewshot = pd.concat([crit_M, bnd_H], ignore_index=True).sample(frac=1, random_state=11)

    prompt_head = OVERRIDE_PREFIX + HEADER
    for _, r in fewshot.iterrows():
        ridx = int(r["row_idx"])
        feats = train.iloc[ridx][FEATURE_KEYS].to_dict()
        score = dgp_score(train.iloc[ridx])
        prompt_head += fmt_few_shot(
            pseudo_id=3000000 + ridx,
            feats=feats,
            amh=float(r["amh"]),
            amm=float(r["amm"]),
            knn_margin=float(r["knn_margin"]),
            bank_max_prob=float(r["bank_max_prob"]),
            bank_split=split_str(ridx),
            sub_votes=subs_str(ridx),
            true_label=r["true_label"],
            score=score,
        ) + "\n"
    prompt_head += ASYMMETRY_NOTE

    # Reuse same critical row order as v2 (eval_keys.csv -> pseudo_id 4000000+row_idx)
    eval_keys = pd.read_csv(OUT / "eval_keys.csv").sort_values("pseudo_id").reset_index(drop=True)

    # batch ~75 rows / batch (smaller than v2's 100 to avoid Read tool budget)
    batch_size = 75
    n_batches = (len(eval_keys) + batch_size - 1) // batch_size

    new_keys = []
    for bi in range(n_batches):
        sub = eval_keys.iloc[bi * batch_size:(bi + 1) * batch_size]
        body = ""
        for _, r in sub.iterrows():
            ridx = int(r["row_idx"])
            feats = train.iloc[ridx][FEATURE_KEYS].to_dict()
            new_pseudo = 5000000 + ridx  # distinct from v2's 4000000+
            body += fmt_row(
                pseudo_id=new_pseudo,
                feats=feats,
                amh=float(r["amh"]),
                amm=0.0,  # amm not in eval_keys; safe default
                knn_margin=float(r["knn_margin"]),
                bank_max_prob=float(r["bank_max_prob"]),
                bank_split=split_str(ridx),
                sub_votes=subs_str(ridx),
            ) + "\n"
            new_keys.append({
                "pseudo_id": new_pseudo,
                "row_idx": ridx,
                "true_label": r["true_label"],
                "amh": float(r["amh"]),
                "knn_margin": float(r["knn_margin"]),
                "bank_max_prob": float(r["bank_max_prob"]),
                "bank_split": split_str(ridx),
                "sub_votes": subs_str(ridx),
                "batch": bi,
            })
        full = prompt_head + body
        out_path = OUT / f"haiku_v3_batch_{bi}.txt"
        out_path.write_text(full)
        print(f"wrote batch {bi}: {out_path}  rows={len(sub)}  chars={len(full)}  ~{len(full) // 4} tokens")

    pd.DataFrame(new_keys).to_csv(OUT / "eval_keys_v3.csv", index=False)
    print(f"\neval_keys_v3: {len(new_keys)} rows")

    # quick stat on bank_split for the critical rows
    splits = [k["bank_split"] for k in new_keys]
    print("\nbank_split distribution on critical rows (top 5):")
    print(pd.Series(splits).value_counts().head(5))


if __name__ == "__main__":
    main()
