"""T1-opus — TRAIN OOF V1-floor validation (single decisive opus call).

Picks 50 TRAIN OOF rows where (bank_argmax=M & fb_oof=H) — the V1 floor
population that hits 81.7% true-M precision in T1_validate_train_oof.py.
Adds 8 few-shot examples from the SAME V1 population with true labels
revealed (mix of true-M and true-H), plus per-row bank max-prob + 5-sub
disagreement vector + an asymmetry note.

Output:
  scripts/artifacts/T1_opus/prompt.txt          — the prompt opus reads
  scripts/artifacts/T1_opus/eval_keys.csv       — test row test_id + true
                                                   label (for scoring)
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from T1_format_batch import FEATURE_KEYS, _format_value  # noqa: E402
from T2_conformal_helpers import bank_mean_probs, load_bank  # noqa: E402
from T6_diversity_helpers import load_y_train, normed, tune_log_bias_simple  # noqa: E402

ART = Path("scripts/artifacts")
DATA = Path("data")
CLASS_STR = {0: "Low", 1: "Medium", 2: "High"}

HEADER = """Task: classify rows of synthetic irrigation-need data as Low / Medium / High.

Background: synthetic data generated by a NN trained on a 10k-row real-world dataset. Reverse-engineered integer rule (~98.4% accurate):

  dry     = (Soil_Moisture < 25)
  norain  = (Rainfall_mm   < 300)
  hot     = (Temperature_C > 30)
  windy   = (Wind_Speed_kmh > 10)
  nomulch = (Mulching_Used == "No")
  Kc      = 2 if Crop_Growth_Stage in {Flowering, Vegetative} else 0
  score   = 2*(dry + norain) + (hot + windy + nomulch) + Kc
  Low if score <= 3 ; Medium if 4 <= score <= 6 ; High if score >= 7

About 1.6% of synthetic rows are flipped by the NN to a neighbouring class based on non-rule features (Humidity, Soil_pH, Previous_Irrigation_mm, Electrical_Conductivity, Organic_Carbon, Sunlight_Hours, Field_Area_hectare, Crop_Type, Region, Season, Soil_Type, Irrigation_Type, Water_Source). The NN tends to over-irrigate when humidity is low + recent irrigation small + organic carbon low.

CRITICAL CONTEXT — these are *hard* cases. All test rows below have:
  - 14-bank tree ensemble argmax = Medium (bank thinks M)
  - LB-validated 4b primary argmax = High (4b thinks H)
On TRAIN OOF, this filter has only 81.7% true-M precision (18% true-H).
The bank is wrong 18% of the time on rows like these; you must decide carefully whether the bank or 4b is right per row.

For each row, output ONE block:

ROW <test_id>
RULE_SCORE: <int>
RULE_PRED: <Low|Medium|High>
FINAL: <Low|Medium|High>      ← your verdict on this row's TRUE label
CONF: <0.0-1.0>               ← your confidence in FINAL
REASON: <<=20 words>

EXAMPLES (8 rows from the same population with TRUE labels revealed; learn from these):

"""

ASYMMETRY_NOTE_BEFORE_TEST = """
Now classify the following 50 rows. Use the same reasoning style as in the examples. Be precise: when the rule + non-rule features clearly point to M, say M with high CONF. When the row LOOKS like the bank may be wrong (rule is solidly H, non-rule features don't suggest a flip down), say H. CONF should reflect how confident you are.

ROWS TO CLASSIFY:

"""


def format_row_with_context(test_id, row_features, bank_mp, four_subs):
    parts = [f"ROW {int(test_id)}"]
    for k in FEATURE_KEYS:
        parts.append(f"{k}={_format_value(k, row_features.get(k))}")
    parts.append(f"bank_max_prob={bank_mp:.3f}")
    parts.append(f"5sub={four_subs}")
    return " ".join(parts)


def format_few_shot(test_id, row_features, bank_mp, true_label, score):
    rp = "Low" if score <= 3 else ("Medium" if score <= 6 else "High")
    parts = [f"ROW {int(test_id)}"]
    for k in FEATURE_KEYS:
        parts.append(f"{k}={_format_value(k, row_features.get(k))}")
    parts.append(f"bank_max_prob={bank_mp:.3f}")
    head = " ".join(parts)
    return (
        f"{head}\n"
        f"RULE_SCORE: {score}\n"
        f"RULE_PRED: {rp}\n"
        f"FINAL: {true_label}    ← TRUE LABEL\n"
        f"CONF: 1.00\n"
        f"REASON: (true label revealed for training; reason it through yourself)\n"
    )


def main():
    print("=== T1 opus TRAIN OOF V1-floor test setup ===\n")
    out_dir = ART / "T1_opus"
    out_dir.mkdir(parents=True, exist_ok=True)

    train = pd.read_csv(DATA / "train.csv")
    y = load_y_train()

    # Build 4b OOF analog (T6_directional_compose.py)
    v1_oof = normed(np.load(ART / "oof_sklearn_rf_meta_natural.npy").astype(np.float32))
    raw_oof = normed(np.load(ART / "oof_rawashishsin_2600.npy").astype(np.float32))
    t1_oof = normed(np.load(ART / "oof_tier1b_greedy_meta.npy").astype(np.float32))
    bv1, _ = tune_log_bias_simple(v1_oof, y)
    bra, _ = tune_log_bias_simple(raw_oof, y)
    bt1, _ = tune_log_bias_simple(t1_oof, y)
    a_v1 = (np.log(np.clip(v1_oof, 1e-9, None)) + bv1).argmax(1).astype(np.int8)
    a_ra = (np.log(np.clip(raw_oof, 1e-9, None)) + bra).argmax(1).astype(np.int8)
    a_t1 = (np.log(np.clip(t1_oof, 1e-9, None)) + bt1).argmax(1).astype(np.int8)
    una = a_ra == a_t1
    fb_oof = a_v1.copy()
    om = una & (a_v1 != a_ra)
    fb_oof[om] = a_ra[om]

    bank = load_bank("oof")
    bank_mean = bank_mean_probs(bank)
    bank_argmax = bank_mean.argmax(axis=1).astype(np.int8)
    bank_max_prob = bank_mean.max(axis=1)

    v1_mask = (bank_argmax == 1) & (fb_oof == 2)
    v1_idx = np.where(v1_mask)[0]
    print(f"V1 floor population: {len(v1_idx)} TRAIN OOF rows")

    # Pick 8 few-shot examples: 4 true-M + 4 true-H, with bank_max_prob in mid range
    rng = np.random.default_rng(42)
    rows_M = [i for i in v1_idx if y[i] == 1]
    rows_H = [i for i in v1_idx if y[i] == 2]
    print(f"  true-M: {len(rows_M)}, true-H: {len(rows_H)}")

    fewshot_M = rng.choice(rows_M, size=4, replace=False).tolist()
    fewshot_H = rng.choice(rows_H, size=4, replace=False).tolist()
    fewshot_idx = list(fewshot_M) + list(fewshot_H)
    rng.shuffle(fewshot_idx)

    # Pick 50 test rows from V1 NOT in few-shot — proportional to V1's true-class mix
    remaining = [i for i in v1_idx if i not in set(fewshot_idx)]
    test_50 = rng.choice(remaining, size=50, replace=False).tolist()
    test_y = np.array([y[i] for i in test_50])
    print(f"  test 50: true-M={int((test_y == 1).sum())}, "
          f"true-H={int((test_y == 2).sum())}, true-L={int((test_y == 0).sum())}")
    print(f"  bank-only true-M precision in this 50-set: {(test_y == 1).mean():.4f}")

    # DGP score
    def dgp_score(row):
        dry = int(row["Soil_Moisture"] < 25)
        norain = int(row["Rainfall_mm"] < 300)
        hot = int(row["Temperature_C"] > 30)
        windy = int(row["Wind_Speed_kmh"] > 10)
        nomulch = int(row["Mulching_Used"] == "No")
        Kc = 2 if row["Crop_Growth_Stage"] in {"Flowering", "Vegetative"} else 0
        return 2 * (dry + norain) + (hot + windy + nomulch) + Kc

    # 5-sub argmaxes (we have these as TRAIN OOF only via fb_oof analogs; for now pass
    # bank_argmax + fb_oof verdicts as the disagreement context, since it's TRAIN OOF)
    def four_subs_str(i):
        return f"bank=M,4b=H,v1={CLASS_STR[a_v1[i]]},raw={CLASS_STR[a_ra[i]]},t1={CLASS_STR[a_t1[i]]}"

    # Build prompt
    prompt = HEADER
    for i in fewshot_idx:
        feats = train.iloc[i][FEATURE_KEYS].to_dict()
        score = dgp_score(train.iloc[i])
        true_lbl = CLASS_STR[y[i]]
        # synthesize a unique pseudo-id for the example so opus doesn't mistake them
        pseudo_id = 1000000 + int(i)
        prompt += format_few_shot(pseudo_id, feats, float(bank_max_prob[i]), true_lbl, int(score)) + "\n"

    prompt += ASYMMETRY_NOTE_BEFORE_TEST
    eval_keys = []
    for i in test_50:
        feats = train.iloc[i][FEATURE_KEYS].to_dict()
        bank_mp = float(bank_max_prob[i])
        line = format_row_with_context(2000000 + int(i), feats, bank_mp, four_subs_str(i))
        prompt += line + "\n"
        eval_keys.append({"pseudo_id": 2000000 + int(i), "row_idx": int(i), "true_label": CLASS_STR[y[i]]})

    out_prompt = out_dir / "prompt.txt"
    out_prompt.write_text(prompt)
    print(f"\nwrote prompt: {out_prompt} ({len(prompt)} chars, ~{len(prompt) // 4} tokens)")

    keys_df = pd.DataFrame(eval_keys)
    keys_df.to_csv(out_dir / "eval_keys.csv", index=False)
    print(f"wrote eval_keys: {out_dir / 'eval_keys.csv'} ({len(keys_df)} rows)")

    print(f"\nbaseline: bank-only true-M rate on this 50-row sample = {(test_y == 1).mean():.4f}")
    print("  (opus needs to beat ~85% to clear the threshold; ~92% to clear test-side break-even)")


if __name__ == "__main__":
    main()
