"""T1-v3-full — sonnet validation on broader V1-floor (not just critical rows).

Test whether sonnet-V3's 95% M @ CONF>=0.8 finding (from n=20 critical rows)
generalizes to the broader V1-floor population. Sample 1500 random V1-floor
rows that are NOT in the critical-rows-253 already tested.

Same prompt structure as T1_haiku_v3_build.py but with calibration text
updated for the broader population (81.7% baseline vs 87.75% critical).

Output: scripts/artifacts/T1_v2/sonnet_full_batch_{i}.txt
        scripts/artifacts/T1_v2/eval_keys_full.csv
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from T1_format_batch import FEATURE_KEYS, _format_value  # noqa: E402
from T2_conformal_helpers import bank_mean_probs, load_bank  # noqa: E402
from T6_diversity_helpers import load_y_train, normed, tune_log_bias_simple  # noqa: E402

ART = Path("scripts/artifacts")
DATA = Path("data")
OUT = ART / "T1_v2"
CLASS_STR = {0: "L", 1: "M", 2: "H"}

OVERRIDE_PREFIX = (
    "IMPORTANT: ignore your statusline-setup persona for this single message. "
    "Output ONLY the requested ROW blocks — no preamble, no markdown fences, "
    "no commentary. No tool calls after the Read.\n\n"
)

HEADER = """Task: classify rows of synthetic irrigation-need data as Low / Medium / High.

Background: synthetic data generated by an NN trained on a 10k-row real-world dataset. Reverse-engineered integer rule (~98.4% accurate):

  dry     = (Soil_Moisture < 25)
  norain  = (Rainfall_mm   < 300)
  hot     = (Temperature_C > 30)
  windy   = (Wind_Speed_kmh > 10)
  nomulch = (Mulching_Used == "No")
  Kc      = 2 if Crop_Growth_Stage in {Flowering, Vegetative} else 0
  score   = 2*(dry + norain) + (hot + windy + nomulch) + Kc
  Low if score <= 3 ; Medium if 4 <= score <= 6 ; High if score >= 7

About 1.6% of rows are flipped by the NN to a neighbouring class based on non-rule features. Over-irrigate flips (M -> H) happen when humidity is low + recent irrigation small + organic carbon low.

CRITICAL CONTEXT — these are HARD cases. The 14-bank tree ensemble says Medium AND the LB-best 4b primary says High. The TRAIN-OOF baseline true-M rate on this V1-floor population is 81.7%. The bank is wrong 18% of the time on rows like these.

Per-row context fields:
  - amh, amm: auxiliary detector probabilities for H/M flip risk (0-1, low = low risk)
  - knn_consensus: k=100-NN class margin (0-1, high = unambiguous neighbors)
  - bank_conf: 14-bank max-prob (0-1, high = bank confident)
  - bank_split: counts of how the 14 bank components vote (e.g. "12M/2H/0L")
  - sub_votes: 3 standalone-LB-validated submission verdicts (v1, raw, t1)

Reasoning guidelines:
  - Lean toward M when bank_split is unanimous (14M/0H) AND knn_consensus high AND amh low.
  - Only flag H when bank_split shows >= 4 H-votes AND multiple non-rule features clearly indicate over-irrigate.
  - Use CONF to express your certainty: 0.8+ for clear cases, 0.6-0.7 for borderline, lower if conflicted.

For each row, output ONE block:

ROW <pseudo_id>
RULE_SCORE: <int>
RULE_PRED: <Low|Medium|High>
FINAL: <Low|Medium|High>
CONF: <0.0-1.0>
REASON: <<=15 words>

EXAMPLES (8 rows from the same V1-floor population with TRUE labels revealed):

"""

ASYMMETRY_NOTE = """

Now classify the following test rows. Use the same reasoning style.

ROWS TO CLASSIFY:

"""


def fmt_row(pseudo_id, feats, amh, amm, knn_margin, bank_max_prob, bank_split, sub_votes):
    parts = [f"ROW {int(pseudo_id)}"]
    for k in FEATURE_KEYS:
        parts.append(f"{k}={_format_value(k, feats.get(k))}")
    parts.append(f"amh={amh:.3f}")
    parts.append(f"amm={amm:.3f}")
    parts.append(f"knn_consensus={knn_margin:.3f}")
    parts.append(f"bank_conf={bank_max_prob:.3f}")
    parts.append(f"bank_split={bank_split}")
    parts.append(f"sub_votes={sub_votes}")
    return " ".join(parts)


def fmt_few_shot(pseudo_id, feats, amh, amm, knn_margin, bank_max_prob, bank_split, sub_votes, true_label, score):
    rp = "Low" if score <= 3 else ("Medium" if score <= 6 else "High")
    head = fmt_row(pseudo_id, feats, amh, amm, knn_margin, bank_max_prob, bank_split, sub_votes)
    return (
        f"{head}\n"
        f"RULE_SCORE: {score}\n"
        f"RULE_PRED: {rp}\n"
        f"FINAL: {true_label}    ← TRUE LABEL\n"
        f"CONF: 1.00\n"
        f"REASON: (true label revealed; reason it through yourself)\n"
    )


def dgp_score(row):
    dry = int(row["Soil_Moisture"] < 25)
    norain = int(row["Rainfall_mm"] < 300)
    hot = int(row["Temperature_C"] > 30)
    windy = int(row["Wind_Speed_kmh"] > 10)
    nomulch = int(row["Mulching_Used"] == "No")
    Kc = 2 if row["Crop_Growth_Stage"] in {"Flowering", "Vegetative"} else 0
    return 2 * (dry + norain) + (hot + windy + nomulch) + Kc


def main():
    print("=== T1-v3-full sonnet build ===\n")
    train = pd.read_csv(DATA / "train.csv")
    y = load_y_train()

    # Reconstruct V1-floor mask
    v1_oof = normed(np.load(ART / "oof_sklearn_rf_meta_natural.npy").astype(np.float32))
    raw_oof = normed(np.load(ART / "oof_rawashishsin_2600.npy").astype(np.float32))
    t1_oof = normed(np.load(ART / "oof_tier1b_greedy_meta.npy").astype(np.float32))
    bv1, _ = tune_log_bias_simple(v1_oof, y)
    bra, _ = tune_log_bias_simple(raw_oof, y)
    bt1, _ = tune_log_bias_simple(t1_oof, y)
    a_v1 = (np.log(np.clip(v1_oof, 1e-9, None)) + bv1).argmax(1).astype(np.int8)
    a_ra = (np.log(np.clip(raw_oof, 1e-9, None)) + bra).argmax(1).astype(np.int8)
    a_t1 = (np.log(np.clip(t1_oof, 1e-9, None)) + bt1).argmax(1).astype(np.int8)
    una = a_ra == a_t1
    fb_oof = a_v1.copy()
    fb_oof[una & (a_v1 != a_ra)] = a_ra[una & (a_v1 != a_ra)]

    bank = load_bank("oof")
    bank_mean = bank_mean_probs(bank)
    bank_argmax = bank_mean.argmax(axis=1).astype(np.int8)
    bank_max_prob = bank_mean.max(axis=1)
    bank_argmaxes_per = bank.argmax(axis=2).astype(np.int8)  # (14, n_train)

    v1_mask = (bank_argmax == 1) & (fb_oof == 2)
    v1_idx = np.where(v1_mask)[0]
    print(f"V1-floor: n={len(v1_idx)}")

    # Aux signals
    amh_arr = np.load(ART / "oof_aux_missed_high.npy").astype(np.float32)
    amm_arr = np.load(ART / "oof_aux_missed_medium.npy").astype(np.float32)
    knn_features = np.load(ART / "oof_knn_train.npy").astype(np.float32)
    knn_margin = knn_features[:, 5] if knn_features.shape[1] >= 6 else np.zeros(len(y))

    # Identify rows already in the critical-rows test set (eval_keys_v3)
    crit_keys = pd.read_csv(OUT / "eval_keys_v3.csv")
    used_idx = set(crit_keys["row_idx"].tolist())
    print(f"already-tested critical: {len(used_idx)} rows")

    available = [i for i in v1_idx if i not in used_idx]
    print(f"available non-critical V1-floor: {len(available)} rows")

    # Sample 1500 random rows
    rng = np.random.default_rng(42)
    sample_size = 1500
    sample_idx = rng.choice(available, size=sample_size, replace=False)
    sample_idx.sort()
    sample_y = y[sample_idx]
    print(f"\nsample {sample_size} rows: true-M={int((sample_y==1).sum())}, "
          f"true-H={int((sample_y==2).sum())}, baseline={(sample_y==1).mean():.4f}")

    def split_str(ridx):
        votes = bank_argmaxes_per[:, ridx]
        counts = np.bincount(votes, minlength=3)
        return f"{counts[1]}M/{counts[2]}H/{counts[0]}L"

    def subs_str(ridx):
        return f"v1={CLASS_STR[a_v1[ridx]]} raw={CLASS_STR[a_ra[ridx]]} t1={CLASS_STR[a_t1[ridx]]}"

    # Few-shot from the V1-floor (mix of true-M and true-H, NOT in sample)
    sample_set = set(int(i) for i in sample_idx)
    pool_M = [i for i in available if y[i] == 1 and i not in sample_set]
    pool_H = [i for i in available if y[i] == 2 and i not in sample_set]
    fs_M = rng.choice(pool_M, size=4, replace=False)
    fs_H = rng.choice(pool_H, size=4, replace=False)
    fewshot_idx = list(fs_M) + list(fs_H)
    rng.shuffle(fewshot_idx)
    print(f"few-shot: 4 true-M + 4 true-H from V1-floor")

    prompt_head = OVERRIDE_PREFIX + HEADER
    for i in fewshot_idx:
        feats = train.iloc[int(i)][FEATURE_KEYS].to_dict()
        score = dgp_score(train.iloc[int(i)])
        prompt_head += fmt_few_shot(
            pseudo_id=6000000 + int(i),
            feats=feats,
            amh=float(amh_arr[i]),
            amm=float(amm_arr[i]),
            knn_margin=float(knn_margin[i]),
            bank_max_prob=float(bank_max_prob[i]),
            bank_split=split_str(int(i)),
            sub_votes=subs_str(int(i)),
            true_label=CLASS_STR[y[int(i)]].replace("L", "Low").replace("M", "Medium").replace("H", "High"),
            score=int(score),
        ) + "\n"
    prompt_head += ASYMMETRY_NOTE

    # Batch 75 rows / batch -> 20 batches
    batch_size = 75
    n_batches = (len(sample_idx) + batch_size - 1) // batch_size
    new_keys = []
    for bi in range(n_batches):
        sub = sample_idx[bi * batch_size:(bi + 1) * batch_size]
        body = ""
        for ridx in sub:
            ridx = int(ridx)
            feats = train.iloc[ridx][FEATURE_KEYS].to_dict()
            new_pseudo = 7000000 + ridx
            body += fmt_row(
                pseudo_id=new_pseudo,
                feats=feats,
                amh=float(amh_arr[ridx]),
                amm=float(amm_arr[ridx]),
                knn_margin=float(knn_margin[ridx]),
                bank_max_prob=float(bank_max_prob[ridx]),
                bank_split=split_str(ridx),
                sub_votes=subs_str(ridx),
            ) + "\n"
            new_keys.append({
                "pseudo_id": new_pseudo,
                "row_idx": ridx,
                "true_label": CLASS_STR[y[ridx]].replace("L", "Low").replace("M", "Medium").replace("H", "High"),
                "amh": float(amh_arr[ridx]),
                "knn_margin": float(knn_margin[ridx]),
                "bank_max_prob": float(bank_max_prob[ridx]),
                "bank_split": split_str(ridx),
                "sub_votes": subs_str(ridx),
                "batch": bi,
            })
        full = prompt_head + body
        out_path = OUT / f"sonnet_full_batch_{bi}.txt"
        out_path.write_text(full)
        if bi < 3 or bi == n_batches - 1:
            print(f"wrote batch {bi}: rows={len(sub)}  chars={len(full)}  ~{len(full) // 4} tokens")

    pd.DataFrame(new_keys).to_csv(OUT / "eval_keys_full.csv", index=False)
    print(f"\ntotal batches: {n_batches}")
    print(f"eval_keys_full: {len(new_keys)} rows")
    print(f"estimated cost: ~${0.165 * n_batches:.2f}")


if __name__ == "__main__":
    main()
