"""W7: k=1 nearest-neighbor of synthetic rows to 10k original.

Mechanism: `brief.md` states train and test were generated by a DL model
trained on the 10k original. Synthetic rows that fall close to an
original row in feature space should inherit that row's label — and
the original's label is rule-perfect by construction.

Diagnostic-only run:
  1) Build a 43-dim feature matrix (11 standardised numerics + 32 one-hot
     cat columns) shared across train, test, and original.
  2) k=1 NN search test→orig and train→orig.
  3) Validate on train: precision(NN-label == y_train) at small τ —
     if it exceeds rule's 98.4% raw accuracy, NN is sharper than rule.
  4) Project to test: override count + agreement-with-primary at the
     same τ. No LB probe without user go-ahead.

Saves artefacts for cross-branch reuse:
  scripts/artifacts/w7_test_nn_{dist,idx,label_idx}.npy
  scripts/artifacts/w7_train_nn_{dist,idx,label_idx}.npy
  scripts/artifacts/w7_nn_to_original_results.json
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
ART = ROOT / "scripts" / "artifacts"
SUB = ROOT / "submissions"

CATS = ["Soil_Type", "Crop_Type", "Crop_Growth_Stage", "Season",
        "Irrigation_Type", "Water_Source", "Mulching_Used", "Region"]
NUMS = ["Soil_pH", "Soil_Moisture", "Organic_Carbon",
        "Electrical_Conductivity", "Temperature_C", "Humidity",
        "Rainfall_mm", "Sunlight_Hours", "Wind_Speed_kmh",
        "Field_Area_hectare", "Previous_Irrigation_mm"]
TARGET = "Irrigation_Need"
CLS = ["Low", "Medium", "High"]
CLS2IDX = {c: i for i, c in enumerate(CLS)}


def log(msg):
    print(msg, flush=True)


def build_X(df, cat_levels, scaler):
    nums = scaler.transform(df[NUMS].to_numpy().astype(np.float32))
    blocks = [nums.astype(np.float32)]
    for c in CATS:
        vals = df[c].astype(str).to_numpy()
        levels = cat_levels[c]
        oh = np.zeros((len(df), len(levels)), dtype=np.float32)
        for k, lev in enumerate(levels):
            oh[vals == lev, k] = 1.0
        blocks.append(oh)
    return np.concatenate(blocks, axis=1)


def main():
    log("--- loading ---")
    train = pd.read_csv(DATA / "train.csv")
    test = pd.read_csv(DATA / "test.csv")
    orig = pd.read_csv(DATA / "irrigation_prediction.csv")
    log(f"  train {train.shape}  test {test.shape}  orig {orig.shape}")

    cat_levels = {c: np.array(sorted(
        set(train[c].astype(str).unique()) |
        set(test[c].astype(str).unique()) |
        set(orig[c].astype(str).unique())
    )) for c in CATS}
    scaler = StandardScaler().fit(orig[NUMS].to_numpy().astype(np.float32))

    X_orig = build_X(orig, cat_levels, scaler)
    X_train = build_X(train, cat_levels, scaler)
    X_test = build_X(test, cat_levels, scaler)
    log(f"  feature dim: {X_orig.shape[1]}")

    log("--- fitting k=1 NN on 10k original ---")
    nn = NearestNeighbors(n_neighbors=1, algorithm="auto", n_jobs=-1)
    nn.fit(X_orig)

    log("--- querying TRAIN (validation: precision vs y_train) ---")
    d_tr, i_tr = nn.kneighbors(X_train, n_neighbors=1)
    d_tr = d_tr.ravel().astype(np.float32)
    i_tr = i_tr.ravel().astype(np.int32)

    log("--- querying TEST ---")
    d_te, i_te = nn.kneighbors(X_test, n_neighbors=1)
    d_te = d_te.ravel().astype(np.float32)
    i_te = i_te.ravel().astype(np.int32)

    orig_labels = np.array([CLS2IDX[l] for l in orig[TARGET].astype(str)])
    y_train = np.array([CLS2IDX[l] for l in train[TARGET].astype(str)])

    log_pct = [0, 0.01, 0.1, 0.5, 1, 2, 5, 10, 25, 50, 75, 99, 100]
    log("--- distance percentiles  TRAIN | TEST ---")
    p_tr = np.percentile(d_tr, log_pct)
    p_te = np.percentile(d_te, log_pct)
    for p, v_tr, v_te in zip(log_pct, p_tr, p_te):
        log(f"  p{p:5.2f}  train={v_tr:.4f}   test={v_te:.4f}")

    log("--- TRAIN validation: precision(NN-label == y_train) at low τ ---")
    log(f"{'tau':>10s} {'n_at_or_below':>15s} {'precision':>12s} {'pct_train':>12s}")
    pred_tr = orig_labels[i_tr]
    val_rows = []
    for pct in [0.01, 0.1, 0.5, 1, 2, 5, 10, 25]:
        tau = np.percentile(d_tr, pct)
        mask = d_tr <= tau
        if mask.sum() == 0:
            continue
        prec = (pred_tr[mask] == y_train[mask]).mean()
        log(f"{tau:>10.4f} {int(mask.sum()):>15d} {prec:>12.5f} {100 * mask.mean():>11.2f}%")
        val_rows.append(dict(tau=float(tau), pct=float(pct),
                             count=int(mask.sum()), precision=float(prec)))

    log("--- TEST projection: count and primary-agreement at the same τ ---")
    primary = pd.read_csv(SUB / "submission_tier1b_greedy_meta.csv")
    primary_idx = np.array([CLS2IDX[l] for l in primary[TARGET].astype(str)])
    pred_te = orig_labels[i_te]
    proj_rows = []
    log(f"{'tau':>10s} {'n_test':>10s} {'agree_primary':>15s} {'overrides':>10s}")
    for r in val_rows:
        tau = r["tau"]
        mask = d_te <= tau
        if mask.sum() == 0:
            continue
        agree = (pred_te[mask] == primary_idx[mask]).mean()
        overrides = int((pred_te[mask] != primary_idx[mask]).sum())
        log(f"{tau:>10.4f} {int(mask.sum()):>10d} {agree:>15.5f} {overrides:>10d}")
        proj_rows.append(dict(tau=float(tau), pct=r["pct"],
                              count=int(mask.sum()),
                              agreement=float(agree),
                              n_overrides=overrides,
                              train_precision=r["precision"]))

    np.save(ART / "w7_test_nn_dist.npy", d_te)
    np.save(ART / "w7_test_nn_idx.npy", i_te)
    np.save(ART / "w7_test_nn_label_idx.npy", pred_te.astype(np.int8))
    np.save(ART / "w7_train_nn_dist.npy", d_tr)
    np.save(ART / "w7_train_nn_idx.npy", i_tr)
    np.save(ART / "w7_train_nn_label_idx.npy", pred_tr.astype(np.int8))

    out = dict(
        n_train=len(train), n_test=len(test), n_orig=len(orig),
        n_features=int(X_orig.shape[1]),
        rule_train_raw_acc_reference=0.98364,
        train_distance_percentiles={f"p{p}": float(v) for p, v in zip(log_pct, p_tr)},
        test_distance_percentiles={f"p{p}": float(v) for p, v in zip(log_pct, p_te)},
        train_validation=val_rows,
        test_projection=proj_rows,
    )
    with open(ART / "w7_nn_to_original_results.json", "w") as f:
        json.dump(out, f, indent=2)
    log(f"--- wrote {ART}/w7_nn_to_original_results.json ---")


if __name__ == "__main__":
    main()
